## eigendecomposition exercise

In [1]:
# import numpy
import numpy as np

**Task:** Create a matrix (2x2) called matrix 'A'.


In [2]:
A = np.array([[1,2], [1,3]])
A

array([[1, 2],
       [1, 3]])

**Task:** Define the function `'shape_2x2'` which checks if a matrix has a (2x2) shape.

In [6]:
"""
Define the function 'shape_2x2' which checks if a matrix has a (2x2) shape.

PARAMS:
    matrix (numpy.ndarray) - matrix to check
RETURN:
    True (bool) - if matrix has shape 2x2
    False (bool) - if matrix has not shape 2x2

"""
def shape_2x2(matrix):
    if matrix.shape ==(2, 2):
        return True
    else:
        return False

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[1, 2, 3], [4, 5, 6]])

print(shape_2x2(matrix1))
print(shape_2x2(matrix2))


True
False


**Task:** Define the function `'determinant_2x2'` which computes the determinant of a (2x2) matrix.

Do not forget to check the shape of  the input matrix.

In [ ]:
"""
Define the function 'determinant_2x2' which computes the determinant of a (2x2) matrix.

PARAMS:
    matrix (numpy.ndarray) - matrix to compute determinant
RETURN:
    det (float) - matrix determinant

"""


In [8]:
def compute_determinant(matrix):
    if matrix.shape == (2, 2):
        a, b = matrix[0, 0], matrix[0, 1]
        c, d = matrix[1, 0], matrix[1, 1]
        determinant = (a * d) - (b * c)
        return determinant
    else:
        raise ValueError("Input matrix must be a (2x2) matrix.")
        
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])


**Task:** Call the function `'determinant_2x2'` on matrix 'A'.

In [9]:

determinant1 = compute_determinant(matrix1)
determinant2 = compute_determinant(matrix2)

print("Determinant of matrix1:", determinant1)
print("Determinant of matrix2:", determinant2)

Determinant of matrix1: -2
Determinant of matrix2: -2


**Task:** Compute the eigenvalues of matrix 'A' with numpy.

In [11]:
eigenvalues = np.linalg.eigvals(A)

**Task:** Print the eigenvalues.

In [12]:
print("Eigenvalues of matrix A:", eigenvalues)

Eigenvalues of matrix A: [0.26794919 3.73205081]


**Task:** Print  the eigenvectors.

In [13]:
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvectors)

[[-0.9390708  -0.59069049]
 [ 0.34372377 -0.80689822]]


**Task:** Define a function `'eig_2x2'` which computes the eigenvectors and the eigenvalues of 2x2 matrix.

Do not use the np.linalg.eig function. Use your 'shape_2x2' and your 'determinant_2x2' functions. Be carefull, eigenvalues and eigenvectors could contain complex numbers.

How to compute eigenvalues of a 2x2 matrix?: Define a function `'eig_2x2'` which computes the eigenvectors and the eigenvalues of 2x2 matrix.


- https://yutsumura.com/express-the-eigenvalues-of-a-2-by-2-matrix-in-terms-of-the-trace-and-determinant/

In [ ]:
"""
Define a function 'eig_2x2' which computes the eigenvectors and the eigenvalues of 2x2 matrix

PARAMS:
    matrix (numpy.ndarray) - matrix to perform decomposition
RETURN:
    eigenvalues, eigenvectors (tuple) - eigenvalues, eigenvectors as numpy.ndarrays

"""

In [14]:
import numpy as np

def eig_2x2(matrix):
    """
    Compute the eigenvalues and eigenvectors of a 2x2 matrix.

    Parameters:
    matrix (numpy.ndarray): The input 2x2 matrix.

    Returns:
    eigenvalues (list): List of eigenvalues.
    eigenvectors (list of numpy.ndarray): List of corresponding eigenvectors.
    """
    if matrix.shape == (2, 2):
        a, b = matrix[0, 0], matrix[0, 1]
        c, d = matrix[1, 0], matrix[1, 1]

        # Compute the eigenvalues using the characteristic equation
        discriminant = np.sqrt((a + d)**2 - 4*(a*d - b*c))
        eigenvalue1 = (a + d + discriminant) / 2
        eigenvalue2 = (a + d - discriminant) / 2

        # Compute the corresponding eigenvectors
        eigenvector1 = np.array([1, (eigenvalue1 - a) / b])
        eigenvector2 = np.array([1, (eigenvalue2 - a) / b])

        # Normalize the eigenvectors
        eigenvector1 /= np.linalg.norm(eigenvector1)
        eigenvector2 /= np.linalg.norm(eigenvector2)

        return [eigenvalue1, eigenvalue2], [eigenvector1, eigenvector2]
    else:
        raise ValueError("Input matrix must be a 2x2 matrix.")



**Task:** Call the function `'eig_2x2'` on matrix 'A'.

In [15]:
# Example usage:
matrix = np.array([[3, 1],
                   [1, 2]])

eigenvalues, eigenvectors = eig_2x2(matrix)

print("Eigenvalues of the matrix:", eigenvalues)
print("Eigenvectors of the matrix:")
for eigenvector in eigenvectors:
    print(eigenvector)

Eigenvalues of the matrix: [3.618033988749895, 1.381966011250105]
Eigenvectors of the matrix:
[0.85065081 0.52573111]
[ 0.52573111 -0.85065081]


**Task:** Compare your results with the numpy function (to compare use the [**np.allclose**](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) function).

**Task:** Define matrix B = np.array([[0,1],[-1,0]]) 

In [17]:
B = np.array([[0, 1], [-1, 0]])
B

array([[ 0,  1],
       [-1,  0]])

**Task:** Compute the eigenvalues and the eigevectors of matrix 'B' with numpy and with your `'eig_2x2'` function.

In [20]:
eigenvalues_custom, eigenvectors_custom = eig_2x2(B)

print("\nEigenvalues and Eigenvectors (Custom Function):")
print("Eigenvalues:", eigenvalues_custom)
print("Eigenvectors:")
for eigenvector in eigenvectors_custom:
    print(eigenvector)


Eigenvalues and Eigenvectors (Custom Function):
Eigenvalues: [nan, nan]
Eigenvectors:
[nan nan]
[nan nan]


C:\Users\davin\AppData\Local\Temp/ipykernel_3120/1426145862.py:19: RuntimeWarning: invalid value encountered in sqrt
  discriminant = np.sqrt((a + d)**2 - 4*(a*d - b*c))


**Task:** Compare the results with the numpy function (to compare use the [**np.allclose**](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) function).

**Task:** Print the eigenvalues and the eigenvectors. Why are the solutions different?